.gitignore
main/win/Config.c
main/win/configdialog.c
main/win/main_win.h
main/win/translation.c
r4300/cop0.c
r4300/cop1_d.c
r4300/cop1_s.c
r4300/macros.h
r4300/pure_interp.c
r4300/r4300.c
r4300/r4300.h
r4300/x86/gcop1_d.c
r4300/x86/gcop1_s.c
winproject/debugview.ini
winproject/mupen64/mupen64_2017.vcxproj
winproject/resource.h
winproject/rsrc.rc

When the checkbox is checked, Mupen will round doubles toward 0, rather than toward the nearest single, when converted. Copy of the logic from SM64-TAS-ABC's RTZ branch, and only works on Dynamic Recompiler.

Implement Wii VC Round-to-Zero

---

main/gui_gtk/main_gtk.c
main/guifuncs.h
main/main.c
main/main_gtk.c
main/savestates.c
main/win/guifuncs.c

Queuecrush is a buffer overflow that results from a .st file encoding more than 1024 event queues. Video about the vulnerability coming soon.

Fix "Queuecrush" bug

---

lua/LuaConsole.cpp

BitBlt behaves unpredictably on some systems, and since the functions NextLuaDC and DrawLuaDC
are only necessary to call when double buffering is enabled BitBlt should only be called when necessary to avoid breaking unbuffered rendering.

Only do BitBlt calls if double buffering is enabled

---

r4300/x86/gcop1_d.c
r4300/x86/gcop1_helpers.c
r4300/x86/gcop1_helpers.h
r4300/x86/gcop1_s.c

Noticed I forgot to pop the x87 stack when handling errors. This causes x87 stack overflows and floating point weirdness to happen when a nan/denormal error for an input rhs occurs for the 6th or so time.
Untested but I feel pretty confident about it.

Clear x87 stack on failed input check

---

main/speex/arch.h
main/speex/speex_resampler.c
main/speex/speex_resampler.h
main/vcr.c
main/vcr_resample.c
winproject/mupen64/mupen64_2017.vcxproj

Main two changes here are replacing the resampler with speex's (https://github.com/xiph/speexdsp) as the previous one was causing audio pops/cracks, and the next main change is redoing the logic on audio sync, which fixes A/V sync where the previous logic failed.

Fix Audio Sync and Audio Pops/Cracking in dumps

---

lua/LuaConsole.cpp

`movie.playmovie(path_to_m64)` will play the M64 movie file at the specified path.
`movie.stopmovie()` will stop the current movie if one is playing.
`emu.atplaymovie(your_code_here)` will execute any code that it is passed once a movie begins playing.
`emu.atstopmovie(your_code_here)` will execute any code that it is passed once the current movie is finished playing, or is stopped using `movie.stopmovie()`.
Example Lua script:
[Movie Functions Example Script.zip](https://github.com/mkdasher/mupen64-rr-lua-/files/8341695/Movie.Functions.Example.Script.zip)

Control Movies from Lua Scripts: 4 New Lua Functions

---

main/savestates.c

This makes the initial save state match the UI, and makes save state slot 0 inaccessible through the UI

Make default save state slot 1 instead of 0

---

main/win/configdialog.c

Anything below 5% isn't handled correctly, which makes emulation run way too fast when set. 5% is the lowest the hotkeys allow, so I thought it was a fine lowest value. If you want to go lower I think frame advance is fine :P 
This also allows realigning to the standard speed up and slow down windows fairly trivially, otherwise you were stuck at 1% higher than expected.

Fixes the slider allowing less than 5% speed

---

main/win/main_win.cpp

I have no idea why lpParam was getting checked here in this way, what does the Rom browser resizing have to do with anything?

Fix closing a ROM not updating the header

---

main/vcr.c

Should prevent movies from finishing until the end of the actual inputs. Ignores the VI's in this case. Fixes #46

Attempt to fix movies stopping too early

---

main/win/wrapper/ReassociatingFileDialog.cpp

This fixes cancelling loading something then cancelling attempting to load something when it shouldn't.

Fix cancelling on file dialog selection

---

main/win/translation.c

The fields were backwards, so it looked wrong. This fixes it

Fix ROM properties dialog

---

main/win/rombrowser.c

Previously, if the freeze option was on on program startup, you couldn't select any recent rom (for some reason). This decouples that functionality, and also fixes the ternary to work properly.

Fix recent rom menu being disabled

---

main/win/main_win.cpp

Slot 0 technically isn't possible to create on new mupen anymore, but I added it here just in case anyone is still using old mupen

Allow slot save states to be loaded through the load savestate menu

---

main/win/CrashHandler.cpp
main/win/timers.cpp

Fixes the timer limit being too low, and also fixes the crash log throwing an exception if brought up with no crash

Fix timer and crash log issues

---

main/vcr.cpp
main/win/main_win.cpp
main/win/translation.c

- `MOVIE_START_FROM_EXISTING_SNAPSHOT` no longer writes its unique flag to the m64 file, instead now using the regular `MOVIE_START_FROM_SNAPSHOT` flag.
- `Toggle Read-Only` GUI button once again displays its associated hotkey

"Start from Existing Snapshot" movie compatibility, GUI fix

---

main/rom.c

the removal of the "Alert Hacked ROMs" config option meant that there was no longer any handling for roms larger than 8,192kb, and such roms would simply fail to load. this fix allows roms up to 65,536kb in size to be loaded (the 512 magic constant is a result of the value returned by `findsize()` on a rom of this size).

fixed roms larger than 8,192kb failing to load

---

main/savestates.c

The `savestates_load` function would only allocate enough memory for savestate filenames using the ".st" extension, and could crash if a savestate filename used the ".savestate" extension. The fix here is to allocate enough memory to accommodate for the ".savestate" extension.

Fixed heap corruption when loading .savestate files

---

main/rom.c

Do this by zeroing out the unused bits. This could potentially cause issues if mupen cares about the checksum at some later point, but I don't think it does.

Fix crashing on roms with garbage data in unused rom header bits

---

main/win/main_win.cpp

This prevents the program from getting stuck if a rom is loaded that fails, for whatever reason.

Show rom browser when rom failed to load

---

main/win/translation.c

"Load Latest Movie" and "Start From Beginning" were displaying the incorrect hotkeys because the `SetHotkeyMenuAccelerator` calls that load them were accessing the wrong indices in the `Config.hotkeys` array.

fixed a couple hotkey accelerator indices in the movie menu

---

main/win/main_win.cpp

This prevents [this](https://github.com/mkdasher/mupen64-rr-lua-/blob/dev/main/win/timers.cpp#L142) from triggering the instant that you press the frame advance key at high speeds.
Setting it to 0 avoids updating the bottom bar (due to [this check](https://github.com/mkdasher/mupen64-rr-lua-/blob/dev/main/win/timers.cpp#L238). Nothing else reads this variable, as it is only used internally to keep track of the status bar at the bottom and the error check mentioned above.

Prevent unnecessary error when running at >1000 VIs and pressing frame advance

---

lua/LuaConsole.cpp

an argument `fontstyle` is now passed to the `wgui.d2d_draw_text` lua function. the valid styles are:
- 0: normal
- 1: bold
- 2: italic
- 3: bold + italic

added font style as parameter to wgui.d2d_draw_text

---

main/win/Config.c
main/win/Config.h
main/win/main_win.cpp

The last author name entered in the author field and the last movie type (from start, from savestate, etc.) are now Config settings.

"Record Movie" dialog box now remembers previous options

---

main/vcr.cpp

Previously, this function failed to free the "bufnExt" buffer (now renamed filenameWithExtension) if the savestate wasn't found. now it's refactored a bit to always free the buffer before returning. A `NULL` check has also been added (mostly to shut up intellisense 😁).

Fixed memory leak in getSavestatePath

---

lua/LuaConsole.cpp

Instead of using a regex to determine when the functions start, using a comment is much easier. Also got rid of some of the broken comments because they were causing issues.

Add comments to help generate lua documentation

---

view/gui/Main.cpp

Pannen's STROOP now has an autoDetect parameter in the Config file which lets STROOP try to auto-detect the RAM start if it doesn't match, most of the emulator entries have it set

Add STROOP autoDetect parameter to Config.xml line

---

src/Core/include/core_api.h
src/Core/r4300/recomp.cpp
src/Core/r4300/recomp.h
src/Core/r4300/tracelog.cpp
src/Views.Win32/lua/LuaConsole.cpp
src/Views.Win32/lua/modules/Memory.h

This is an API set that has previously existed, but disappeared during the memory API refactor.
This PR introduces the relevant core API and implements the Lua layer.

Implement Lua memory APIs: recompilenow, recompile, recompilenext, recompilenextall

---

src/Views.Win32/lua/LuaRegistry.cpp
src/Views.Win32/lua/modules/Emu.h
tools/mupenapi.lua

Removed `emu.setgfx` as it previously did nothing
Restructured and reformatted mupenapi.lua
- removed `printx` as it has been deprecated
- added emulator state warning to all `emu.atxyz` function except `emu.atvi` and `emu.atinput`
- added strong typing for `input.get` and `joypad.get`

Update api file
