- mupen64_input/main.c
> Layout and language consistency

- README.md
- main/win/Config.c
Saves the settings like 3 miliseconds faster or something i dont remember
> Mupen slightly faster closing™ and better indentation style

- main/mupenIniApi.c
- main/win/main_win.cpp
Saves only when settings menu was opened
> Save only when necessary and Confirm closing if movie is being recorded

- main/win/main_win.cpp
This fixes offscreen recording and black bars when dragging from offscreen.
> Fix offscreen recording

- r4300/cop1_d.c
- r4300/cop1_s.c
- r4300/macros.h
- r4300/pure_interp.c
I've tested that this compiles on gcc and the asm looks fine, but not that it actually works (since Linux build is broken). Neither have I tested it on MSVC.
> gcc float conversions, and fix non-pure interp as well

- main/vcr.c
Tested to fix the issue on the specified ROM, also verified to properly reset between different ROM loads
> Fix unknown country code warning reprompting on every frame

- main/win/Config.c
- main/win/main_win.cpp
- main/win/main_win.h
- winproject/resource.h
- winproject/rsrc.rc
new menu item underneath the "Recent ROMs" menu in the gui, and can be activated with the hotkey "Ctrl + Shift + L"
> added "Load Latest ROM" option

- main/win/Config.c
- main/win/configdialog.c
This also has my prior change in #51 since I have no idea what happened to that.
> Fix FPS Bar, ensure FPS will be in valid range when loading config

- main/win/configdialog.c
- main/win/main_win.cpp
- main/win/translation.c
- winproject/rsrc.rc
Also fixes the one random hotkey in the Run menu (the hotkey[44] line)
> Move Movie menu out of Utilities

- lua/LuaConsole.cpp
Documentation:
`nil wgui.clearimage(int clearIndex)`
Clears an image from imagePool at location clearIndex. If clearIndex is 0, all images in imagePool are deleted.
`nil wgui.drawimagescale(int imgIndex, int left, int top, number xscale, number yscale)`
Identical to wgui.drawimage, but with scaling.
> Added wgui.clearimage and wgui.drawimagescale

- main/win/main_win.cpp
I tested most ways that this can interact, but its a pain trying to check every dialog box / feature. Its possible I missed some things due to multithreading weirdness. I couldn't seem to find any issues currently.
> Remove resume -> pause on menu selection

- main/vcr.cpp
- main/win/main_win.cpp
this was really annoying and was causing me to overwrite movie files
> fixed a couple places where movies wouldn't start in read-only mode

- .editorconfig
- lua/LuaConsole.cpp
- main/win/DebugInfo.hpp
- main/win/timers.cpp
loadscreen is only working about 50% of the time. sometimes it works perfectly and sometimes the HBITMAP is null.
> Clean up d2d functions and port loadscreen to d2d (WIP)

- README.md
> Fix Discord link in readme

- main/vcr.cpp
Previously, the precautionary savestate existence check would fail to find savestate files that had periods `.` in the filename, even when it had the same name as the m64 file being loaded. This PR fixes this behavior.
> startPlayback can now find savestates with `.` in the filename

- main/win/Config.cpp
- main/win/Config.hpp
- main/win/configdialog.c
- main/win/vcr_compress.c
- winproject/resource.h
- winproject/rsrc.rc
Adds settings that Pannen wanted. These are in the "Advanced options" dialog. This should be ready to merge but I couldn't do a final test because the dev branch seems not to be working rn
> Add "Capture other windows" and "Capture delay" settings

- main/vcr.cpp
- main/win/Config.cpp
- main/win/CrashHandlerDialog.cpp
- main/win/configdialog.c
- main/win/main_win.cpp
- r4300/pure_interp.c
Changes that shouldn't affect any functionality, just cleaning up some compiler warnings/dead code
> Clean up some warnings

- memory/memory.cpp
- memory/memory.h
- r4300/rom.cpp
Reverts mkdasher/mupen64-rr-lua-#205
> Revert "Use VirtualAlloc for rom and ram buffers"

- view/gui/Main.cpp
- view/gui/features/Statusbar.cpp
- view/gui/features/Statusbar.hpp
Also fixes a bug where the status bar didn't initialize correctly when the window was too small
> Add separate section for read-only status

- tools/mupenapi.lua
The api file contains definitions for all of mupen's builtin lua functions. Moved from [here](https://github.com/Wade7wastaken/MupenLuaDoc).
> Add lua api file to /tools

- src/Core/include/core_api.h
- src/Core/r4300/vcr.cpp
- src/Views.Win32/gui/Main.cpp
This restores the previous behavior of older Mupen versions.
> Main/Chg: End captures when movie playback stops or loops

- src/Views.Win32/Config.h
- src/Views.Win32/DialogService.cpp
- src/Views.Win32/DialogService.h
- src/Views.Win32/components/UpdateChecker.cpp
- Added changelog dialog 
- Improved error reporting
- Removed useless ignore button
> Better update checker

- lib/lust.lua
- test/lua/mupen64.lua
- test/lua/prelude.lua
This also adds a test for #317
> test(Lua): lua testing infrastructure

- src/Views.Win32/components/LuaDialog.cpp
- src/Views.Win32/lua/LuaManager.cpp
- src/Views.Win32/lua/LuaManager.h
- src/Views.Win32/lua/LuaTypes.h
avoids even more horrible state management confusion
> split Lua environment creation and starting into two steps

- Plugins.Audio.Dummy.vcxproj
- Plugins.Input.Dummy.vcxproj
- Plugins.RSP.Dummy.vcxproj
- Plugins.Video.Dummy.vcxproj
- Plugins.props
- mupen64.sln
- src/Core/include/core_api.h
- src/Core/include/core_plugin.h
- src/Plugins.Audio.Dummy/Main.cpp
- src/Plugins.Audio.Dummy/Main.h
- src/Plugins.Input.Dummy/Main.cpp
- src/Plugins.Input.Dummy/Main.h
- src/Plugins.RSP.Dummy/Main.cpp
- src/Plugins.RSP.Dummy/Main.h
- src/Plugins.Video.Dummy/Main.cpp
- src/Plugins.Video.Dummy/Main.h
This PR moves the "No Plugin" suite into the mupen64-rr-lua repository.
Closes #389
> Move No Plugin suite into mupen64 repo
